export default function Home() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-semibold tracking-tight">Code Tutorial</h1>
      <p className="mt-3 text-[var(--color-fg-muted)]">
        Interactive tutorials, generated by an agent, for understanding any codebase.
      </p>
    </main>
  );
}
