import path from "node:path";
import { discoverTutorials, loadTutorial } from "@/lib/tutorials";
import { TutorialCard } from "@/components/TutorialCard";

const TUTORIALS_DIR = path.join(process.cwd(), "public/tutorials");

export default async function Home() {
  const slugs = await discoverTutorials(TUTORIALS_DIR);
  const tutorials = await Promise.all(slugs.map((s) => loadTutorial(TUTORIALS_DIR, s)));
  tutorials.sort((a, b) => (b.generatedAt ?? "").localeCompare(a.generatedAt ?? ""));

  return (
    <main className="mx-auto max-w-5xl px-6 py-16">
      <header className="mb-10">
        <h1 className="text-3xl font-semibold tracking-tight">Code Tutorial</h1>
        <p className="mt-2 text-[var(--color-fg-muted)]">
          Interactive tutorials, generated by an agent, for understanding any codebase.
        </p>
      </header>

      {tutorials.length === 0 ? (
        <p className="text-[var(--color-fg-muted)]">
          No tutorials yet. Run the agent pipeline to generate one.
        </p>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2">
          {tutorials.map((t) => (
            <TutorialCard
              key={t.slug}
              slug={t.slug}
              name={t.name}
              summary={t.summary}
              generatedAt={t.generatedAt}
            />
          ))}
        </div>
      )}
    </main>
  );
}
